name: 'Set up .NET environment'
description: 'Sets up .NET SDK, caches NuGet packages, and restores dependencies.'

inputs:
  working-directory:
    description: 'Project working directory'
    required: true
    type: string
  dotnet-version:
    description: '.NET SDK version'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Create NuGet cache folder
      run: mkdir -p ~/.nuget/packages

    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      working-directory: "./${{ inputs.working-directory }}"
      run: dotnet restore
