name: 'Set up .NET SDK'
description: 'This action sets up .NET SDK, caches dependencies, and restores project dependencies'

inputs:
  working-directory:
    description: 'Project working directory'
    required: true
    type: string
  dotnet-version:
    description: '.NET SDK version'
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Setup .NET SDK
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    # Step 3: Create NuGet cache folder
    - name: Create NuGet cache folder
      run: mkdir -p ~/.nuget/packages
      shell: bash
      
    # Step 4: Cache NuGet packages
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Step 5: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore
      working-directory: "./${{ inputs.working-directory }}"
      shell: bash
